export const outfitCategories = [
  { id: "daily", label: "Daily" },
  { id: "professional", label: "Professional" },
  { id: "formal", label: "Formal" },
  { id: "athletic", label: "Athletic" },
  { id: "travel", label: "Travel" },
  { id: "weather_protective", label: "Weather" }
];

export const categoryOptions = [
  "top",
  "bottom",
  "outerwear",
  "dress",
  "suit",
  "shoes",
  "accessory",
  "athletic",
  "underwear",
  "socks",
  "sleepwear",
  "swimwear"
];

export const seasonOptions = ["spring", "summer", "fall", "winter"];
export const climateOptions = ["hot", "mild", "cool", "cold", "rain", "wind", "snow"];
export const laundryOptions = ["ready", "worn", "dirty", "repair"];
export const slotOrder = ["outerwear", "top", "bottom", "shoes", "accessory"];

export const weatherPresets = [
  { id: "cool-dry", label: "Cool dry", tempF: 52, rainPct: 8, windMph: 9, season: "fall" },
  { id: "mild-office", label: "Mild office", tempF: 67, rainPct: 12, windMph: 6, season: "spring" },
  { id: "hot-humid", label: "Hot humid", tempF: 86, rainPct: 28, windMph: 5, season: "summer" },
  { id: "rain-commute", label: "Rain commute", tempF: 58, rainPct: 82, windMph: 18, season: "spring" },
  { id: "winter-wind", label: "Winter wind", tempF: 28, rainPct: 18, windMph: 24, season: "winter" }
];

const item = (data) => ({
  status: "active",
  laundry: "ready",
  wears: 0,
  condition: 4,
  warmth: 3,
  breathability: 3,
  rain: 1,
  wind: 1,
  formality: 2,
  materialPct: 100,
  outfitTags: ["daily"],
  season: ["spring", "fall"],
  climate: ["mild"],
  pattern: "solid",
  care: "machine wash",
  storageLocation: "closet",
  notes: "",
  ...data
});

export const starterItems = [
  item({
    id: "itm-navy-merino",
    name: "Navy merino crew",
    category: "top",
    subcategory: "knit shirt",
    brand: "North Loom",
    size: "M",
    color: "Navy",
    swatch: "oklch(0.31 0.055 258)",
    material: "Merino wool",
    fabric: "fine jersey knit",
    warmth: 4,
    breathability: 4,
    formality: 3,
    cost: 98,
    acquired: "2024-10-12",
    wears: 18,
    lastWorn: "2026-06-27",
    outfitTags: ["daily", "professional", "travel"],
    season: ["fall", "winter", "spring"],
    climate: ["cool", "cold", "mild"],
    layerRole: "base",
    notes: "Good base layer for cold offices."
  }),
  item({
    id: "itm-white-oxford",
    name: "White oxford shirt",
    category: "top",
    subcategory: "button-down",
    brand: "Ledger House",
    size: "M",
    color: "White",
    swatch: "oklch(0.96 0.003 210)",
    material: "Cotton",
    fabric: "oxford cloth",
    warmth: 2,
    formality: 4,
    cost: 72,
    acquired: "2023-04-04",
    wears: 31,
    lastWorn: "2026-06-21",
    outfitTags: ["professional", "formal", "travel"],
    season: ["spring", "summer", "fall"],
    climate: ["mild", "hot"],
    layerRole: "base",
    care: "machine wash, hang dry"
  }),
  item({
    id: "itm-black-tee",
    name: "Black heavyweight tee",
    category: "top",
    subcategory: "t-shirt",
    brand: "Ward Standard",
    size: "M",
    color: "Black",
    swatch: "oklch(0.16 0.005 230)",
    material: "Cotton",
    fabric: "heavy jersey",
    warmth: 2,
    breathability: 3,
    formality: 1,
    cost: 38,
    acquired: "2025-05-19",
    wears: 25,
    lastWorn: "2026-06-29",
    outfitTags: ["daily", "travel"],
    season: ["spring", "summer", "fall"],
    climate: ["mild", "hot"],
    layerRole: "base"
  }),
  item({
    id: "itm-linen-shirt",
    name: "Stone linen camp shirt",
    category: "top",
    subcategory: "short sleeve shirt",
    brand: "Harbor Grid",
    size: "M",
    color: "Stone",
    swatch: "oklch(0.78 0.014 95)",
    material: "Linen",
    fabric: "plain weave",
    warmth: 1,
    breathability: 5,
    formality: 2,
    cost: 86,
    acquired: "2024-06-06",
    wears: 14,
    lastWorn: "2026-06-15",
    outfitTags: ["daily", "travel"],
    season: ["summer"],
    climate: ["hot"],
    layerRole: "base"
  }),
  item({
    id: "itm-chambray",
    name: "Washed chambray shirt",
    category: "top",
    subcategory: "button-down",
    brand: "Mill Standard",
    size: "M",
    color: "Light blue",
    swatch: "oklch(0.72 0.055 235)",
    material: "Cotton",
    fabric: "chambray",
    warmth: 2,
    breathability: 4,
    formality: 2,
    cost: 78,
    acquired: "2021-03-12",
    wears: 48,
    lastWorn: "2026-05-30",
    outfitTags: ["daily", "travel"],
    season: ["spring", "summer", "fall"],
    climate: ["mild", "hot"],
    condition: 3
  }),
  item({
    id: "itm-charcoal-trouser",
    name: "Charcoal technical trouser",
    category: "bottom",
    subcategory: "trouser",
    brand: "Vector Cloth",
    size: "32x30",
    color: "Charcoal",
    swatch: "oklch(0.30 0.012 245)",
    material: "Nylon elastane blend",
    materialPct: 92,
    fabric: "stretch woven",
    warmth: 3,
    breathability: 3,
    rain: 2,
    wind: 3,
    formality: 4,
    cost: 128,
    acquired: "2025-02-18",
    wears: 22,
    lastWorn: "2026-06-24",
    outfitTags: ["daily", "professional", "travel"],
    season: ["spring", "fall", "winter"],
    climate: ["mild", "cool", "wind"]
  }),
  item({
    id: "itm-denim",
    name: "Dark straight denim",
    category: "bottom",
    subcategory: "jeans",
    brand: "Mill Standard",
    size: "32",
    color: "Indigo",
    swatch: "oklch(0.34 0.062 252)",
    material: "Cotton denim",
    materialPct: 98,
    fabric: "12 oz twill",
    warmth: 3,
    breathability: 2,
    formality: 2,
    cost: 118,
    acquired: "2022-11-10",
    wears: 54,
    lastWorn: "2026-06-19",
    outfitTags: ["daily", "travel"],
    season: ["fall", "winter", "spring"],
    climate: ["cool", "cold", "mild"],
    condition: 3
  }),
  item({
    id: "itm-linen-trouser",
    name: "Taupe linen trouser",
    category: "bottom",
    subcategory: "trouser",
    brand: "Harbor Grid",
    size: "32",
    color: "Taupe",
    swatch: "oklch(0.64 0.028 75)",
    material: "Linen cotton",
    materialPct: 55,
    fabric: "plain weave",
    warmth: 1,
    breathability: 5,
    formality: 3,
    cost: 112,
    acquired: "2025-06-02",
    wears: 6,
    lastWorn: "2026-06-03",
    outfitTags: ["daily", "professional", "travel"],
    season: ["summer"],
    climate: ["hot"]
  }),
  item({
    id: "itm-running-short",
    name: "Black running shorts",
    category: "athletic",
    subcategory: "shorts",
    brand: "Kinetic Field",
    size: "M",
    color: "Black",
    swatch: "oklch(0.19 0.006 230)",
    material: "Recycled polyester",
    materialPct: 88,
    fabric: "stretch woven",
    warmth: 0,
    breathability: 5,
    rain: 2,
    formality: 1,
    cost: 58,
    acquired: "2024-05-21",
    wears: 39,
    lastWorn: "2026-06-26",
    outfitTags: ["athletic", "travel"],
    season: ["summer", "spring"],
    climate: ["hot", "rain"]
  }),
  item({
    id: "itm-navy-suit",
    name: "Navy wool suit",
    category: "suit",
    subcategory: "two-piece suit",
    brand: "Civic Tailor",
    size: "40R / 32",
    color: "Navy",
    swatch: "oklch(0.28 0.053 258)",
    material: "Wool",
    fabric: "worsted twill",
    warmth: 3,
    breathability: 3,
    formality: 5,
    cost: 680,
    acquired: "2020-02-14",
    wears: 22,
    lastWorn: "2026-04-18",
    outfitTags: ["formal", "professional"],
    season: ["spring", "fall", "winter"],
    climate: ["mild", "cool"],
    care: "dry clean",
    storageLocation: "garment bag",
    condition: 3
  }),
  item({
    id: "itm-rain-shell",
    name: "Graphite rain shell",
    category: "outerwear",
    subcategory: "shell jacket",
    brand: "Ridgeline Lab",
    size: "M",
    color: "Graphite",
    swatch: "oklch(0.36 0.016 220)",
    material: "Recycled nylon membrane",
    fabric: "3-layer waterproof shell",
    warmth: 1,
    breathability: 3,
    rain: 5,
    wind: 5,
    formality: 2,
    cost: 240,
    acquired: "2024-03-09",
    wears: 16,
    lastWorn: "2026-06-28",
    outfitTags: ["daily", "travel", "weather_protective"],
    season: ["spring", "summer", "fall"],
    climate: ["rain", "wind"],
    layerRole: "shell"
  }),
  item({
    id: "itm-wool-blazer",
    name: "Deep teal wool blazer",
    category: "outerwear",
    subcategory: "blazer",
    brand: "Civic Tailor",
    size: "40R",
    color: "Deep teal",
    swatch: "oklch(0.39 0.078 196)",
    material: "Wool",
    fabric: "tropical wool",
    warmth: 3,
    breathability: 3,
    formality: 5,
    cost: 310,
    acquired: "2023-09-13",
    wears: 12,
    lastWorn: "2026-06-12",
    outfitTags: ["professional", "formal"],
    season: ["spring", "fall"],
    climate: ["mild", "cool"],
    layerRole: "mid"
  }),
  item({
    id: "itm-down-parka",
    name: "Black down parka",
    category: "outerwear",
    subcategory: "parka",
    brand: "Ridgeline Lab",
    size: "M",
    color: "Black",
    swatch: "oklch(0.17 0.006 230)",
    material: "Nylon and down",
    materialPct: 70,
    fabric: "down insulated shell",
    warmth: 5,
    breathability: 1,
    rain: 3,
    wind: 5,
    formality: 2,
    cost: 420,
    acquired: "2019-12-02",
    wears: 75,
    lastWorn: "2026-02-12",
    outfitTags: ["daily", "travel", "weather_protective"],
    season: ["winter"],
    climate: ["cold", "snow", "wind"],
    layerRole: "insulation",
    condition: 2
  }),
  item({
    id: "itm-brown-derby",
    name: "Brown derby shoes",
    category: "shoes",
    subcategory: "derby",
    brand: "Foundry Last",
    size: "10.5",
    color: "Brown",
    swatch: "oklch(0.42 0.082 55)",
    material: "Full-grain leather",
    fabric: "leather upper",
    warmth: 2,
    breathability: 2,
    formality: 4,
    cost: 210,
    acquired: "2021-08-30",
    wears: 67,
    lastWorn: "2026-06-23",
    outfitTags: ["professional", "formal", "travel"],
    season: ["spring", "fall", "winter"],
    climate: ["mild", "cool"],
    care: "condition leather"
  }),
  item({
    id: "itm-black-oxford",
    name: "Black oxford shoes",
    category: "shoes",
    subcategory: "oxford",
    brand: "Foundry Last",
    size: "10.5",
    color: "Black",
    swatch: "oklch(0.16 0.005 230)",
    material: "Calf leather",
    fabric: "leather upper",
    warmth: 2,
    formality: 5,
    cost: 260,
    acquired: "2018-09-20",
    wears: 44,
    lastWorn: "2026-04-18",
    outfitTags: ["formal", "professional"],
    season: ["spring", "fall", "winter"],
    climate: ["mild", "cool"],
    condition: 2,
    care: "polish"
  }),
  item({
    id: "itm-trail-runner",
    name: "Black trail runners",
    category: "shoes",
    subcategory: "running shoe",
    brand: "Kinetic Field",
    size: "10.5",
    color: "Black",
    swatch: "oklch(0.19 0.006 230)",
    material: "Mesh and rubber",
    materialPct: 74,
    fabric: "engineered mesh",
    warmth: 1,
    breathability: 5,
    rain: 3,
    formality: 1,
    cost: 135,
    acquired: "2025-07-14",
    wears: 44,
    lastWorn: "2026-06-29",
    outfitTags: ["daily", "athletic", "travel", "weather_protective"],
    season: ["spring", "summer", "fall"],
    climate: ["hot", "rain", "mild"]
  }),
  item({
    id: "itm-winter-boot",
    name: "Insulated winter boots",
    category: "shoes",
    subcategory: "boot",
    brand: "Ridgeline Lab",
    size: "10.5",
    color: "Black",
    swatch: "oklch(0.18 0.006 230)",
    material: "Leather rubber wool",
    materialPct: 60,
    fabric: "waterproof boot",
    warmth: 5,
    rain: 4,
    wind: 3,
    formality: 1,
    cost: 190,
    acquired: "2020-11-04",
    wears: 52,
    lastWorn: "2026-02-10",
    outfitTags: ["daily", "travel", "weather_protective"],
    season: ["winter"],
    climate: ["snow", "cold", "rain"],
    condition: 3
  }),
  item({
    id: "itm-field-watch",
    name: "Field watch",
    category: "accessory",
    subcategory: "watch",
    brand: "Minute Works",
    size: "40 mm",
    color: "Olive",
    swatch: "oklch(0.43 0.057 128)",
    material: "Steel and nylon",
    materialPct: 80,
    fabric: "woven strap",
    warmth: 0,
    breathability: 3,
    rain: 4,
    formality: 2,
    cost: 160,
    acquired: "2020-01-20",
    wears: 190,
    lastWorn: "2026-06-29",
    outfitTags: ["daily", "professional", "travel", "weather_protective"],
    season: ["spring", "summer", "fall", "winter"],
    climate: ["hot", "mild", "cool", "rain"]
  }),
  item({
    id: "itm-silk-tie-burgundy",
    name: "Burgundy silk tie",
    category: "accessory",
    subcategory: "tie",
    brand: "Ledger House",
    size: "58 in",
    color: "Burgundy",
    swatch: "oklch(0.34 0.098 25)",
    material: "Silk",
    pattern: "subtle stripe",
    warmth: 0,
    formality: 5,
    cost: 62,
    acquired: "2019-05-10",
    wears: 18,
    lastWorn: "2026-04-18",
    outfitTags: ["formal", "professional"],
    season: ["fall", "winter", "spring"],
    climate: ["mild", "cool"],
    care: "dry clean"
  }),
  item({
    id: "itm-wool-scarf",
    name: "Gray wool scarf",
    category: "accessory",
    subcategory: "scarf",
    brand: "North Loom",
    size: "one size",
    color: "Gray",
    swatch: "oklch(0.56 0.008 230)",
    material: "Lambswool",
    warmth: 4,
    wind: 3,
    formality: 3,
    cost: 74,
    acquired: "2022-12-01",
    wears: 36,
    lastWorn: "2026-02-11",
    outfitTags: ["daily", "professional", "travel", "weather_protective"],
    season: ["winter"],
    climate: ["cold", "wind", "snow"],
    layerRole: "accessory"
  }),
  item({
    id: "itm-leather-belt",
    name: "Brown leather belt",
    category: "accessory",
    subcategory: "belt",
    brand: "Foundry Last",
    size: "34",
    color: "Brown",
    swatch: "oklch(0.42 0.082 55)",
    material: "Leather",
    formality: 4,
    cost: 72,
    acquired: "2021-08-30",
    wears: 130,
    lastWorn: "2026-06-23",
    outfitTags: ["daily", "professional", "formal", "travel"],
    season: ["spring", "summer", "fall", "winter"],
    climate: ["hot", "mild", "cool"]
  }),
  item({
    id: "itm-wool-socks",
    name: "Charcoal merino socks",
    category: "socks",
    subcategory: "dress sock",
    brand: "North Loom",
    size: "L",
    color: "Charcoal",
    swatch: "oklch(0.30 0.012 245)",
    material: "Merino nylon",
    materialPct: 70,
    warmth: 3,
    breathability: 4,
    formality: 4,
    cost: 18,
    acquired: "2025-01-08",
    wears: 32,
    lastWorn: "2026-06-22",
    outfitTags: ["daily", "professional", "formal", "travel"],
    season: ["spring", "fall", "winter"],
    climate: ["mild", "cool", "cold"]
  }),
  item({
    id: "itm-running-socks",
    name: "White running socks",
    category: "socks",
    subcategory: "athletic sock",
    brand: "Kinetic Field",
    size: "L",
    color: "White",
    swatch: "oklch(0.96 0.003 210)",
    material: "Nylon polyester",
    materialPct: 78,
    warmth: 1,
    breathability: 5,
    formality: 1,
    cost: 14,
    acquired: "2025-07-01",
    wears: 50,
    lastWorn: "2026-06-29",
    outfitTags: ["athletic", "travel"],
    season: ["spring", "summer", "fall"],
    climate: ["hot", "mild"]
  }),
  item({
    id: "itm-performance-polo",
    name: "Forest performance polo",
    category: "top",
    subcategory: "polo",
    brand: "Kinetic Field",
    size: "M",
    color: "Forest",
    swatch: "oklch(0.38 0.08 145)",
    material: "Polyester elastane",
    materialPct: 92,
    fabric: "pique knit",
    warmth: 1,
    breathability: 5,
    rain: 2,
    formality: 2,
    cost: 64,
    acquired: "2025-04-23",
    wears: 12,
    lastWorn: "2026-06-18",
    outfitTags: ["daily", "athletic", "travel"],
    season: ["summer", "spring"],
    climate: ["hot", "rain", "mild"]
  }),
  item({
    id: "itm-gym-hoodie",
    name: "Heather gym hoodie",
    category: "athletic",
    subcategory: "hoodie",
    brand: "Kinetic Field",
    size: "M",
    color: "Heather gray",
    swatch: "oklch(0.66 0.008 230)",
    material: "Cotton polyester fleece",
    materialPct: 65,
    fabric: "brushed fleece",
    warmth: 4,
    breathability: 2,
    formality: 1,
    cost: 74,
    acquired: "2022-10-11",
    wears: 88,
    lastWorn: "2026-06-25",
    outfitTags: ["daily", "athletic", "travel"],
    season: ["fall", "winter", "spring"],
    climate: ["cool", "cold"],
    condition: 2
  }),
  item({
    id: "itm-swim-trunk",
    name: "Teal swim trunks",
    category: "swimwear",
    subcategory: "swim trunk",
    brand: "Harbor Grid",
    size: "M",
    color: "Teal",
    swatch: "oklch(0.52 0.105 190)",
    material: "Recycled nylon",
    materialPct: 92,
    warmth: 0,
    breathability: 5,
    rain: 5,
    formality: 1,
    cost: 68,
    acquired: "2021-06-18",
    wears: 20,
    lastWorn: "2025-08-20",
    outfitTags: ["travel", "athletic"],
    season: ["summer"],
    climate: ["hot", "rain"],
    storageLocation: "seasonal bin"
  }),
  item({
    id: "itm-sleep-pant",
    name: "Plaid sleep pants",
    category: "sleepwear",
    subcategory: "sleep pant",
    brand: "Home Loom",
    size: "M",
    color: "Navy plaid",
    swatch: "oklch(0.31 0.055 258)",
    material: "Cotton flannel",
    fabric: "flannel",
    pattern: "plaid",
    warmth: 4,
    breathability: 2,
    formality: 1,
    cost: 42,
    acquired: "2020-11-22",
    wears: 110,
    lastWorn: "2026-06-20",
    outfitTags: ["daily"],
    season: ["winter", "fall"],
    climate: ["cold", "cool"],
    condition: 2
  }),
  item({
    id: "itm-white-undershirt",
    name: "White undershirt pack",
    category: "underwear",
    subcategory: "undershirt",
    brand: "Basics Co",
    size: "M",
    color: "White",
    swatch: "oklch(0.96 0.003 210)",
    material: "Cotton",
    warmth: 1,
    breathability: 4,
    formality: 1,
    cost: 28,
    acquired: "2024-01-05",
    wears: 80,
    lastWorn: "2026-06-28",
    outfitTags: ["daily", "professional", "formal", "travel"],
    season: ["spring", "summer", "fall", "winter"],
    climate: ["hot", "mild", "cool", "cold"],
    condition: 3
  }),
  item({
    id: "itm-burgundy-dress",
    name: "Burgundy wrap dress",
    category: "dress",
    subcategory: "wrap dress",
    brand: "Civic Tailor",
    size: "M",
    color: "Burgundy",
    swatch: "oklch(0.34 0.098 25)",
    material: "Viscose",
    materialPct: 95,
    fabric: "crepe knit",
    warmth: 2,
    breathability: 3,
    formality: 4,
    cost: 148,
    acquired: "2023-10-07",
    wears: 9,
    lastWorn: "2026-05-02",
    outfitTags: ["professional", "formal", "travel"],
    season: ["spring", "fall"],
    climate: ["mild", "cool"],
    care: "delicate wash"
  }),
  item({
    id: "itm-wool-overcoat",
    name: "Camel wool overcoat",
    category: "outerwear",
    subcategory: "overcoat",
    brand: "Civic Tailor",
    size: "M",
    color: "Camel",
    swatch: "oklch(0.63 0.065 72)",
    material: "Wool cashmere",
    materialPct: 90,
    fabric: "double-faced wool",
    warmth: 5,
    breathability: 2,
    rain: 1,
    wind: 4,
    formality: 5,
    cost: 520,
    acquired: "2017-11-11",
    wears: 82,
    lastWorn: "2026-02-01",
    outfitTags: ["professional", "formal", "travel", "weather_protective"],
    season: ["winter"],
    climate: ["cold", "wind"],
    layerRole: "outer",
    condition: 2,
    care: "dry clean"
  }),
  item({
    id: "itm-rain-hat",
    name: "Waxed rain cap",
    category: "accessory",
    subcategory: "hat",
    brand: "Ridgeline Lab",
    size: "M",
    color: "Olive",
    swatch: "oklch(0.39 0.06 130)",
    material: "Waxed cotton",
    warmth: 1,
    breathability: 2,
    rain: 4,
    wind: 2,
    formality: 1,
    cost: 46,
    acquired: "2023-04-18",
    wears: 24,
    lastWorn: "2026-06-28",
    outfitTags: ["daily", "travel", "weather_protective"],
    season: ["spring", "fall"],
    climate: ["rain", "wind"]
  }),
  item({
    id: "itm-olive-chino",
    name: "Olive stretch chinos",
    category: "bottom",
    subcategory: "chino",
    brand: "Ward Standard",
    size: "32x30",
    color: "Olive",
    swatch: "oklch(0.43 0.057 128)",
    material: "Cotton elastane",
    materialPct: 97,
    fabric: "stretch twill",
    warmth: 2,
    breathability: 3,
    formality: 3,
    cost: 88,
    acquired: "2024-09-04",
    wears: 19,
    lastWorn: "2026-06-17",
    outfitTags: ["daily", "professional", "travel"],
    season: ["spring", "summer", "fall"],
    climate: ["mild", "hot"]
  }),
  item({
    id: "itm-black-ponte-pant",
    name: "Black ponte pants",
    category: "bottom",
    subcategory: "knit pant",
    brand: "Civic Tailor",
    size: "M",
    color: "Black",
    swatch: "oklch(0.16 0.005 230)",
    material: "Rayon nylon elastane",
    materialPct: 68,
    fabric: "ponte knit",
    warmth: 3,
    breathability: 3,
    formality: 4,
    cost: 118,
    acquired: "2023-11-14",
    wears: 27,
    lastWorn: "2026-06-10",
    outfitTags: ["daily", "professional", "travel"],
    season: ["fall", "winter", "spring"],
    climate: ["mild", "cool"]
  }),
  item({
    id: "itm-thermal-base",
    name: "Charcoal thermal base layer",
    category: "top",
    subcategory: "base layer",
    brand: "North Loom",
    size: "M",
    color: "Charcoal",
    swatch: "oklch(0.30 0.012 245)",
    material: "Merino nylon",
    materialPct: 86,
    fabric: "thermal knit",
    warmth: 5,
    breathability: 4,
    formality: 1,
    cost: 84,
    acquired: "2024-12-03",
    wears: 15,
    lastWorn: "2026-02-08",
    outfitTags: ["daily", "athletic", "travel", "weather_protective"],
    season: ["winter"],
    climate: ["cold", "snow", "wind"],
    layerRole: "base"
  }),
  item({
    id: "itm-weather-dress-boot",
    name: "Black weather dress boots",
    category: "shoes",
    subcategory: "dress boot",
    brand: "Foundry Last",
    size: "10.5",
    color: "Black",
    swatch: "oklch(0.16 0.005 230)",
    material: "Water-resistant leather",
    fabric: "sealed leather upper",
    warmth: 3,
    breathability: 2,
    rain: 4,
    wind: 3,
    formality: 4,
    cost: 245,
    acquired: "2024-10-28",
    wears: 11,
    lastWorn: "2026-05-11",
    outfitTags: ["professional", "formal", "travel", "weather_protective"],
    season: ["fall", "winter", "spring"],
    climate: ["rain", "cool", "cold"],
    care: "condition leather"
  }),
  item({
    id: "itm-packable-sun-hat",
    name: "Packable sun hat",
    category: "accessory",
    subcategory: "hat",
    brand: "Harbor Grid",
    size: "M",
    color: "Sand",
    swatch: "oklch(0.73 0.04 83)",
    material: "Paper straw polyester",
    materialPct: 85,
    fabric: "woven straw",
    warmth: 0,
    breathability: 5,
    formality: 1,
    cost: 36,
    acquired: "2025-06-12",
    wears: 8,
    lastWorn: "2026-06-14",
    outfitTags: ["daily", "travel"],
    season: ["summer"],
    climate: ["hot"]
  })
];
